# Generated by Django 6.0.6 on 2026-06-20 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        max_length=11,
                    ),
                ),
                (
                    "play_mode",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("front9", "Front 9"),
                            ("back9", "Back 9"),
                        ],
                        default="full",
                        max_length=6,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("current_hole", models.PositiveSmallIntegerField(default=1)),
                ("total_strokes", models.IntegerField(blank=True, null=True)),
                ("total_par", models.IntegerField(blank=True, null=True)),
                ("relative_to_par", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rounds",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="RoundHole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hole_number", models.PositiveSmallIntegerField()),
                ("par", models.PositiveSmallIntegerField()),
                ("strokes", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holes",
                        to="rounds.round",
                    ),
                ),
            ],
            options={
                "ordering": ["hole_number"],
            },
        ),
        migrations.CreateModel(
            name="Shot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shot_number", models.PositiveSmallIntegerField()),
                ("club", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "round_hole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shots",
                        to="rounds.roundhole",
                    ),
                ),
            ],
            options={
                "ordering": ["shot_number"],
            },
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(fields=["user"], name="rounds_roun_user_id_cf16c2_idx"),
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(fields=["status"], name="rounds_roun_status_8e7067_idx"),
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(
                fields=["course"], name="rounds_roun_course__ddc4a5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "in_progress")),
                fields=("user",),
                name="uq_user_one_in_progress_round",
            ),
        ),
        migrations.AddConstraint(
            model_name="roundhole",
            constraint=models.UniqueConstraint(
                fields=("round", "hole_number"), name="uq_round_hole_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="shot",
            constraint=models.UniqueConstraint(
                fields=("round_hole", "shot_number"), name="uq_round_hole_shot_number"
            ),
        ),
    ]
