# Generated by Django 6.0.7 on 2026-07-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
